{
 "title": "Docker Registry Proxy",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Cache HIT Ratio",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "drp_cache_hits / (drp_cache_hits + drp_cache_misses)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Auth SUCCESS rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "drp_auth_successes / (drp_auth_successes + drp_auth_failures)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests IMAGE",
   "type": "table",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(drp_requests_image) by (image)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests TOTAL",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "drp_requests_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Requests GET",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "drp_requests_get", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Requests HEAD 7d",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "drp_requests_head", "legendFormat": "__auto" }
   ]
  }
 ]
}